---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: attrage-app-5
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: attrage-v5
  policy:
    numerical:
      order: asc
