---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: attrage-app-51
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: ^b
  imageRepositoryRef:
    name: attrage-v5
  policy:
    alphabetical:
      order: asc
