---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: attrage-v5
  namespace: flux-system
spec:
  image: kamiq.skoda.roy.lab/kpack/attrage-app-5
  interval: 1m0s
  certSecretRef:
    name: harboaca
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
